### ISSUE TITLE
Script for removing double (ore more) spaces between words

### ISSUE THREAD

**Issue by cpohli** [amebalabs/Esse#12]
Hi there :-)

Would it be possible to make a script that transforms **double (or more) spaces into only one space**?

Tnaks you very much!

**Comment by melonamin** [comment]
Hey,

have you tried "Remove White Space"? It truncates empty space, including empty lines, tabs and multiple spaces

**Comment by cpohli** [comment]
Ah, uh - missed that.
I was under the impression it removes ALL spaces.
This is the right answer for my question (although it seems to leave empty lines?).

Thanky you for pointing in the right direction!

**Comment by melonamin** [comment]
> although it seems to leave empty lines?

There is "Remove Empty Lines" action in Esse, you can chain these two and save as your own, custom transform.

**Comment by cpohli** [comment]
I sometimes get texts, where there a many double spaces between words and double (or more) empty lines between paragraphs.
It would be nice to have the "remove empty lines" to act like "remove white spaces" - leave 1 empty line, when there are more than 1. 
Most of the times one empty line is intended by the writer (as are one spaces between words :-)) and they just hit space or enter several times accidently during writing.

But i can live with that, the lines are way easier to spot than double spaces between words :-)

**EDIT:** forget about that, i just found the "remove duplicate lines" - exactly what i need!
Now i can combine those two, as you pointed out, and am all set. :-)
