### ISSUE TITLE
Esse CLI (and Alfred workflow by extension) fails on "- " input

### ISSUE THREAD

**Issue by mishamsk** [amebalabs/Esse#16]
For some reason, a dash followed by a space and then pretty much anything "crashes" the CLI:

```
/Applications/Esse.app/Contents/MacOS/EsseCommandLine -i "- "
Error: Missing value for '-i <i>'
Usage: esse [-t <t>] [-i <i>] <subcommand>
  See 'esse --help' for more information.
```

**Comment by melonamin** [comment]
Looks like it is a by design behavior. 

Adding `=` fixes the issue, like this `/Applications/Esse.app/Contents/MacOS/EsseCommandLine -i="- "`. I've updated the workflow

**Comment by mishamsk** [comment]
Thanks!
