### ISSUE TITLE
Can't locate folder for external scripts

### ISSUE THREAD

**Issue by villeodell** [amebalabs/Esse#4]
Hi there! I can't seem to locate the folder Esse uses for external scripts. 

I read the help page:
> External scripts are stored in Esse’ folder on iCloud drive, you can access it in Files app on iOS and in Finder on macOS. Esse monitors this folder for changes and refreshes scripts automatically, but you can do it manually as well from app settings.

I don't have an Esse folder in my iCloud drive after installing Esse on both macOS and iPadOS. I tried creating an Esse folder myself in my iCloud drive and putting a script in  both `/Esse/ExternalScript.js` and `/Esse/scripts/ExternalScript.js` but that didn't do anything.

I have the feeling I might be missing something obvious, but I can't figure out what it is.

**Comment by melonamin** [comment]
Thank you, it's a known issue, iCloud folder is not created in some cases, I'm working on an update, stay tuned.

On Mac you can set a custom folder through app's menu, on iOS there is no workaround

**Comment by melonamin** [comment]
@villeodell check out [this build](https://github.com/amebalabs/Esse/releases/tag/2021.2-beta-1)
