### ISSUE TITLE
Chicago Manual of Style adds additional line break

### ISSUE THREAD

**Issue by mishamsk** [amebalabs/Esse#6]
Hi,

When applying the Chicago Manual of Style conversion it adds (duplicates) "\n" at the end of the string. Also, some of the other built-in functions I've tried actually remove existing line break (e.g. Camel case, Capitalize words). Pretty annoying in PPTX/Word where auto-select prefers to select line break alongside a string

**Comment by melonamin** [comment]
I can't seem to reproduce this behavior, can you please share a screen recording?

**Comment by mishamsk** [comment]
![here you go](https://user-images.githubusercontent.com/5206955/127813984-6f762e8a-b2f5-48aa-9283-eab4fa814a94.gif)
here you go

**Comment by mishamsk** [comment]
TIL alfred apparently imitates Command-C/Command-V and somehow blocks Cleanshot from capturing the Command-Shift-E

**Comment by melonamin** [comment]
On a first glance it looks like a bug or "specific behavior" in PowerPoint, look at this example:

![CleanShot 2021-08-02 at 18 00 59](https://user-images.githubusercontent.com/222100/127929452-be2bafa6-9077-47db-a090-b48a38628c48.gif)

When you copy a line of text from PP it adds a newline for whatever reason. You probably can combine "Remove New Lines" and "Chicago Manual of Style" actions in a custom one and use it for PP.

Just for the sake of it: Sublime Text works as expected:

![CleanShot 2021-08-02 at 17 54 58](https://user-images.githubusercontent.com/222100/127928992-640a2f52-b705-4cb4-8ce0-6c0d36d64a88.gif)

**Comment by mishamsk** [comment]
bummer. I can't seem to find a way for CLI to list custom functions though, so Alfred workflow won't work here. Feature request?

**Comment by melonamin** [comment]
Try [this one ](https://github.com/amebalabs/Esse/releases/tag/2021.2-beta-1)

**Comment by mishamsk** [comment]
hm. I took the new one from release, but it seems like it the same one
![CleanShot 2021-08-07 at 12 15 54@2x](https://user-images.githubusercontent.com/5206955/128595464-86790108-191c-4198-9441-c560f745e60c.png)

**Comment by melonamin** [comment]
This is the correct build (225), I forgot to bump the version.

I think the problem is that you have custom script directory configured, switch to the default one in iCloud drive - `defaults write com.ameba.esse PluginDirectory ""`
