### ISSUE TITLE
“Smart Quotes” doesn’t smarten single quotes?

### ISSUE THREAD

**Issue by handcoding** [amebalabs/Esse#9]
It would seem that Esse’s “Smart Quotes” function doesn’t smarten single quotes. Here’s a test case: 

`"I  don't '80s or walking."`

The output from that is:

`“I  don't '80s or walking.”`

The output that I’d expect is:

`“I  don’t ’80s or walking.”`

Other details:
* This is with Esse 2020.5 (218).
* My Mac is on macOS Catalina 10.15.7.
* I would’ve upgraded to the latest Esse release, but it would seem that 2020.5 is the last version that still works on macOS 10.15?

![Esse 2020 5 - Smart Quotes](https://user-images.githubusercontent.com/118319/140086567-32790405-26da-4792-a7fb-84f94bb4ee01.png)

**Comment by melonamin** [comment]
Hi @handcoding, 

yes, you’re correct, single quotes are not handled by this functions, only double. I’m not sure why, judging by descriptions it should be both.

I’ll change this behavior and try to rollback the deployment target back to 10.15, I actually don’t see any reason why this wouldn’t work.

**Comment by handcoding** [comment]
Big, big thanks for both of those things (the coming single-quotes support and the coming macOS 10.15 support). That means a lot!

PS I also have a second machine that’s on 10.14 Mojave. I don’t suppose there’s any chance that you might be able to target back that far? Or nah?

**Comment by melonamin** [comment]
Try this build, it should run 10.15 and do what you expect. [Esse Standalone.app.zip](https://github.com/amebalabs/Esse/files/7491157/Esse.Standalone.app.zip)

As for 10.14 - no, this is a Catalyst app(shared codebase with the iPadOS), 10.15 is the minimum target. I'm thinking of redoing the UI, but even then 10.15 would be the minimum, maybe even 11.
